//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramUploader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AscendDbEntities : DbContext
    {
        public AscendDbEntities()
            : base("name=AscendDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AscendUser> AscendUsers { get; set; }
        public virtual DbSet<Movement> Movements { get; set; }
        public virtual DbSet<ProgramHeader> ProgramHeaders { get; set; }
        public virtual DbSet<ProgramHeaderMovement> ProgramHeaderMovements { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
