//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramUploader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramHeaderMovement
    {
        public int Id { get; set; }
        public int ProgramHeaderId { get; set; }
        public int MovementId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Reps { get; set; }
        public Nullable<int> Sets { get; set; }
        public string Notes { get; set; }
        public string RPE { get; set; }
    
        public virtual Movement Movement { get; set; }
        public virtual ProgramHeader ProgramHeader { get; set; }
    }
}
